---
# OS Pre-reqs 

- name: update all packages
  yum:
    name: "*"
    state: latest
    exclude: docker-engine,docker-engine-selinux
  when: system_updates

- name: install prereqs 
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - ipset
    - ntp
    - firewalld
    - vim-enhanced
    - vim-common
    - bind-utils
    - ipset
    - java-1.7.0-openjdk

- name: disable selinux
  selinux:  
    state: disabled

- name: create group 'nogroup'
  group: 
    name: nogroup 
    state: present

- name: ensure ipv6 is not disabled
  sysctl: name={{ item }} value=0 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: disable chronyd
  service:
    name: chronyd
    enabled: no
    state: stopped

- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: set TZ to EST
  timezone:
    name: America/New_York