---
# This playbook installs docker

- name: enable overlay module
  lineinfile:
    dest: /etc/modules-load.d/overlay.conf
    state: present
    create: yes
    line: 'overlay'

- name: load overlay module
  modprobe:
    name: overlay
    state: present

- name: enable docker yum repo
  template:
    src: docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644

- name: create docker systemd directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: 0755

- name: configure docker to use overlay 
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0644
    force: yes
  notify:
    - restart docker

- name: install docker packages
  yum:
    name: "docker-engine-{{ docker_version }}, docker-engine-selinux-{{ docker_version }}"
    update_cache: yes
    state: present

- name: enable docker
  service:
    name: docker
    enabled: yes
    state: started

- name: logrotate for docker 
  template:
    src: docker.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: 0644 
